### ISSUE TITLE
Interaction doesn't show if "duplicated"

### ISSUE THREAD

**Issue by VIRUXE** [Sleepless-Development/sleepless_interact#1]
I redid one of the `addCoords` I have, restarted the resource and it stopped showing.

```
[sleepless_interact] [WARN] duplicate interaction id added: police:keyLocker
error during NUI callback setCurrentTextOption: @sleepless_interact/client/main.lua:22: attempt to index a nil value (upvalue 'ActiveInteraction')
```

**Comment by DemiAutomatic** [comment]
Yeah i need to add caching for invoking resources and destroy the interacts that belong to the restarted resource. Currently it should delete the old one with the same id and just make the new one so thats odd

**Comment by DemiAutomatic** [comment]
Did you change any parameters? From before to after it stopped working?

**Comment by VIRUXE** [comment]
> Did you change any parameters? From before to after it stopped working?

Added distance, changed label and canInteract return

**Comment by VIRUXE** [comment]
Also added another option, restarted the resource and it only shows the first registered.

Restarted interact, restarted my resource and everything stopped showing. But if I reconnect everything works.

**Comment by DemiAutomatic** [comment]
I discovered a syntax error for onResource start that was causing the dui to reload when any script restarted. That was causing the issue with the first registered interact applying to other things and also just not showing anything sometimes

**Comment by DemiAutomatic** [comment]
The canInteract issue is also resolved

**Comment by VIRUXE** [comment]
Fixed.
