### ISSUE TITLE
Option groups not filtering

### ISSUE THREAD

**Issue by VIRUXE** [Sleepless-Development/sleepless_interact#2]
```lua
{
	text = 'Apresentar Queixa',
          icon = 'exclamation',
          action = function(data) 
		print(json.encode(data, { indent = true })) 
	end
},
{
	text = 'Preencher Formulário de Candidatura',
	icon = 'file-contract',
	groups = { ['police'] = 3 },
	action = function(data) 
		print(json.encode(data, { indent = true })) 
	end
},
{
	text = 'Requisitar Informação',
	icon = 'question',
	action = function(data) 
		print(json.encode(data, { indent = true })) 
	end
}
```
![image](https://github.com/Sleepless-Development/sleepless_interact/assets/1616657/babbaba8-65e7-4675-9bb4-e965582a0a0c)

I'm set to the last police grade.
![image](https://github.com/Sleepless-Development/sleepless_interact/assets/1616657/a6e01ca6-b832-48cb-a0bb-620ec516de38)

ESX.PlayerData.job
![image](https://github.com/Sleepless-Development/sleepless_interact/assets/1616657/7f8a92c5-e702-4769-8f1c-febb27803ff6)

**Comment by DemiAutomatic** [comment]
Maybe im crazy, but that seems correct. It should show for any rank that is 3 or higher. You are currently rank 4

**Comment by VIRUXE** [comment]
You're probably right. Was having a long day at the time. 
Anyway, I've updated to the latest version, compiled the web folder and am now getting this error: `SCRIPT ERROR: @sleepless_interact/imports/utils.lua:184: bad argument #1 to 'for iterator' (table expected, got nil)` - which from what I've seen in the code, is related to the groups.

My code remains the same.

**Comment by DemiAutomatic** [comment]
is this still an issue as of now?

**Comment by VIRUXE** [comment]
```
git pull
cd web
pnpm i && pnpm build
```
```
refresh
restart sleepless_interact
restart police
spawned
pressed LALT
went near the marker
```

![image](https://github.com/Sleepless-Development/sleepless_interact/assets/1616657/6532c991-bc76-45e6-9ad8-86433908a914)

The Release package is triggering a severe virus intervention with Windows Defender.

**Comment by VIRUXE** [comment]
Alright so the blank DUI was apparently related to Windows Defender flagging some files.

And the rest has been fixed in the latest commit.
