### ISSUE TITLE
Unintended ox_inventory dependency

### ISSUE THREAD

**Issue by lynexer** [Sleepless-Development/sleepless_interact#5]
The `imports/utils.lua` file requires the `@ox_inventory.data.vehicles` object from ox_inventory. From what I have found searching through the resource, it seems that this is only used is you are using the ox core bridge and have the defaults enabled for opening ox inventory via a vehicles truck vehicle bone. However, even when not using ox core, it is currently required to have ox_inventory installed in order to properly import that dependency declared in `imports/utils.lua`.

In my personal implementation I have created an `imports/vehicles.lua` file that enables me to just ignore this issue without making too many breaking changes, but that doesn't seem like the best way to maintain the configuration gained from using said import in the first place.

**Comment by DemiAutomatic** [comment]
Yeah thats an oversight on my end. I should just be able to make it a conditional dependency for if ox_inventory is started or not


edit: it wouldnt/shouldnt really be a dependency, but just a conditional extra feature that handles the positioning of the trunk access for ox_inv users
